print("Welcome to the Band Name Generator.")
print("****************************************************")
city = input("What's the name of the city you grew up in?\n")
print("****************************************************")
pet = input("What's the name of your pet?\n")
print("****************************************************")
print("Your band name could be " + city + " " + pet)
